# Generated by Django 3.2.8 on 2021-12-14 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.mediaPath


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=utils.mediaPath.brandIcon)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=utils.mediaPath.brandIcon)),
            ],
            options={
                'verbose_name': 'Brands',
                'verbose_name_plural': 'Brands',
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands')),
            ],
            options={
                'verbose_name': 'catalogue',
                'verbose_name_plural': 'catalogue',
                'db_table': 'catalogue',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('sort_description', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catalogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'db_table': 'Products',
                'unique_together': {('catalogue', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('images', models.ImageField(upload_to=utils.mediaPath.productImage)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Prodcut Images',
                'db_table': 'ProdcutImages',
            },
        ),
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.mediaPath.categoryIcon)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands')),
            ],
            options={
                'verbose_name': 'Modals',
                'verbose_name_plural': 'Modals',
                'db_table': 'Modals',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=utils.mediaPath.categoryImage)),
                ('icon', models.ImageField(upload_to=utils.mediaPath.categoryIcon)),
                ('parent', models.ManyToManyField(blank=True, null=True, related_name='_products_category_parent_+', to='products.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Cateogry',
                'db_table': 'Category',
            },
        ),
        migrations.AddField(
            model_name='catalogue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='modal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.modal'),
        ),
    ]
