# Generated by Django 3.2.8 on 2021-10-09 06:35

from django.db import migrations, models
import utils.mediaPath


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=utils.mediaPath.categoryImage)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Cateogry',
                'db_table': 'Category',
            },
        ),
    ]
